all:
	cd ./Agent/C && make
	cd ./Agent/Java && make
	cd ./Agent/Python && make

	cd ./Environment/C && make
	cd ./Environment/Java && make
	cd ./Environment/Python && make

	cd ./Experiment/C && make
	cd ./Experiment/Java && make
	cd ./Experiment/Python && make

	cd ./Glue_single_C_exe && make

clean:

	cd ./Agent/C && make clean
	cd ./Agent/Java && make clean
	cd ./Agent/Python && make clean

	cd ./Environment/C && make clean
	cd ./Environment/Java && make clean
	cd ./Environment/Python && make clean

	cd ./Experiment/C && make clean
	cd ./Experiment/Java && make clean
	cd ./Experiment/Python && make clean

	cd ./Glue_single_C_exe && make clean
