LDFLAGS := $(LDFLAGS)
CFLAGS := $(CFLAGS) -Wall -pedantic

all: SampleSarsaAgent

SampleSarsaAgent: SampleSarsaAgent.o 
	$(CC)  $(LDFLAGS) SampleSarsaAgent.o -lrlutils -lrlagent -lrlgluenetdev -o SampleSarsaAgent      

SampleSarsaAgent.o: SampleSarsaAgent.c
	$(CC)  $(CFLAGS) -c SampleSarsaAgent.c -o SampleSarsaAgent.o 

clean:
	rm -rf SampleSarsaAgent SampleSarsaAgent.exe *.o









