#!/bin/bash
rm -Rf ./windows-binaries/rl-glue-trunk
svn export http://rl-glue.googlecode.com/svn/trunk ./windows-binaries/rl-glue-trunk
cd ./windows-binaries/rl-glue-trunk
./configure --host i586-mingw32msvc --enable-mingw
make
cp ./src/rl_glue.exe ../tmp.exe
./configure
make clean
make
VERSION=`./src/rl_glue --pv`
cd ..
mv tmp.exe rl_glue-$VERSION.exe
svn up
svn add rl_glue-$VERSION.exe
svn commit -m "Latest autogenerated Windows binary."

