LDFLAGS := $(LDFLAGS)
CFLAGS := $(CFLAGS) -Wall -pedantic

all: SampleMinesEnvironment

SampleMinesEnvironment: SampleMinesEnvironment.o 
	$(CC)  $(LDFLAGS) SampleMinesEnvironment.o -lrlutils -lrlenvironment -lrlgluenetdev -o SampleMinesEnvironment      

SampleMinesEnvironment.o: SampleMinesEnvironment.c
	$(CC)  $(CFLAGS) -c SampleMinesEnvironment.c -o SampleMinesEnvironment.o 

clean:
	rm -rf SampleMinesEnvironment SampleMinesEnvironment.exe *.o









